copy F:\Oracle\Middleware\oracle_common\modules\oracle.owasp_11.1.1\xercesImpl-2.9.1.jar  z:\pablo\lib\EPM4\ z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-mapping.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-utility.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-collation.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-translation.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-net.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-servlet.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-lcsd.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.nlsrtl_11.1.0\orai18n-tools.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-pool-1.6.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\datadirect_4.1\wlsqlserver.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\datadirect_4.1\wldb2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-dbcp-1.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-exec-1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.xalan_2.7.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.xml.serializer_2.7.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\hfm\11.1.2.0\lib\fm-web-objectmodel.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\thrift\11.1.2.0\lib\libthrift-0.9.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\thrift\11.1.2.0\lib\slf4j-api-1.5.8.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\thrift\11.1.2.0\lib\slf4j-log4j12-1.5.8.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\loggers\Log4j\1.2.14\lib\log4j-1.2.14.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\org.apache.commons.beanutils_1.8.3.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\soa\modules\commons-cli-1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-codec-1.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.commons.collections_3.2.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.owasp_11.1.1\commons-configuration-1.5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-dbcp-1.4.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\org.apache.commons.digester_1.8.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-discovery-0.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.adf.share_11.1.1\commons-el.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.owasp_11.1.1\commons-fileupload-1.2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-httpclient-3.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-io-1.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.owasp_11.1.1\commons-lang-2.3.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\org.apache.commons.logging_1.1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.commons.net_1.0.0.0_1-4-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.commons.pool_1.3.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\commons-validator-1.3.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.regexp_1.0.0.0_1-4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\lucene-core-1.9.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\lucene-analyzers-1.9.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\lucene-spellchecker-1.9.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\JakartaCommons\jakarta-commons.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\hfm\11.1.2.0\lib\fm-adm-driver.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\hfm\11.1.2.0\lib\hssutil.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\hfm\11.1.2.0\lib\fmcommon.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\hfm\11.1.2.0\lib\fm-actions.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\lcmclient.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_hfm_server.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_hfm_web.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\registry-api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\CSS\11.1.2.0\lib\css.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\CSS\11.1.2.0\lib\ldapbp.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\wlpool.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\audit-client.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\wf_ces_utils.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\wf_eng_agent.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\wf_eng_api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\interop-sdk.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\commons-compress-1.5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\xmlrpc-2.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\javascript\1.6.5\js.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\XML\StAX\1.0.1\stax-api-1.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\ctg_custom.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\ctg.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.iau_11.1.1\fmw_audit.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.idm_11.1.1\identitystore.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.idm_11.1.1\identityutils.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jacc-spi.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-unsupported-api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-common.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-ee.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-internal.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-mbeans.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jps_11.1.1\jps-wls.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.ldap_11.1.1\ldapjclnt11.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.osdt_11.1.1\osdt_core.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.osdt_11.1.1\osdt_cert.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.pki_11.1.1\oraclepki.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.xdk_11.1.0\xmlparserv2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache_1.3.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.i18n_1.9.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.logging_1.9.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils.full_1.10.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils.wrapper_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils.classloaders_2.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.providers.env_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.saml2.manage_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.web.api_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.rmi.client_1.11.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.transaction_2.7.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.workarea_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.xml.weblogic.xpath_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.datasource6_1.10.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.stax_1.10.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wls-api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.security.jacc_1.0.0.0_1-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jdbc_11.1.1\ojdbc6dms.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.vmm.client_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.vmm.client.adapter.ovm22.ws_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\features\weblogic.server.modules.wlsve_10.3.6.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.antlr.runtime_2.7.7.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.descriptor.j2ee_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.descriptor.j2ee.binding_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.descriptor.wl_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.descriptor.wl.binding_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.datasource6.binding_1.10.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.beangen_1.7.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.descriptor.settable.binding_1.7.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.accessor_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.accessor.binding_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.management.core_2.9.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.management.core.binding_2.9.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.ejbgen_1.1.0.3.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant.patch_1.2.0.0_1-7-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-antlr.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-apache-bcel.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-apache-bsf.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-apache-log4j.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-apache-oro.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-apache-regexp.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-apache-resolver.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-commons-logging.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-commons-net.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-jai.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-javamail.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-jdepend.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-jmf.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-jsch.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-junit.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-launcher.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-netrexx.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-nodeps.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-starteam.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-stylebook.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-swing.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-testutil.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-trax.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-weblogic.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\xml-apis.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.ant_1.7.1\lib\ant-all.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.apache.bcel_5.2.2.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.jdt_3.5.3.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.commons.lang_2.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.commons.io_1.0.0.0_1-4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.commons.fileupload_1.0.0.0_1-2-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.dom_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.logging_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.apache.openjpa_1.3.0.0_1-1-1-SNAPSHOT.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.xml.xmlbeans_2.2.0.0_2-5-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.bea.opensaml_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.bea.opensaml2_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.monitoring.harvester.api_2.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.monitoring.harvester.jmx_2.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.adaptive.harvester.utils_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.mbean.typing.util_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javolution_3.7.19.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\joda.time_1.2.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.xml.staxb.buildtime_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.xml.staxb.runtime_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.annogen_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.kodo_1.5.0.0_4-2-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.kodo.integration_1.7.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.kodo.integration.binding_1.7.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.kodo.integration.tools_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils_1.10.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.xml.beaxmlbeans_2.5.0.0_2-5-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.aspectj.aspectjweaver_5.3.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.apache.commons.logging_1.2.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.springframework.spring_1.2.0.0_2-5-3.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.springframework.pitchfork_1.4.0.0_1-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.spring.instrument_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.i18n_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.xacml_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.saml2.utils_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.engine.impl_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.engine.api_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.api_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.impl_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.jdkutils_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.utils_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.saml2_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.providers.utils_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.saml.utils_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.common.security.xacmlproviders.utils_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.certj_5.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.ldapjdk_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.saaj_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.el_1.1.0.0_2-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxb_1.1.0.0_2-1-14.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxb.xjc_1.2.0.0_2-1-14.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxws.resolver_1.0.0.0_2-1-5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxws.fastinfoset_1.0.0.0_2-1-5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxws.rt_1.3.0.0_2-1-5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxws.mimepull_1.1.0.0_1-3.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.stax2_1.0.0.0_3-0-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.woodstox_1.0.0.0_4-0-5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.jaxws.tools_1.2.0.0_2-1-5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.stax.ex_1.0.0.0_1-2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\glassfish.xmlstreambuffer_1.0.0.0_0-5-279.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.oro_1.0.0.0_2-0-8.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.activation_1.1.0.0_1-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.annotation_1.0.0.0_1-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.interceptor_1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.ejb_3.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.jdo_2.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.enterprise.deploy_1.2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.jms_1.1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.jsp_1.3.0.0_2-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.jws_2.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.mail_1.1.0.0_1-4-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.management.j2ee_1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.persistence_1.0.0.0_1-0-2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.resource_1.5.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.servlet_1.0.0.0_2-5.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.transaction_1.0.0.0_1-1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.xml.bind_2.1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.xml.registry_1.0.0.0_1-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.xml.soap_1.3.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.xml.stream_1.1.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.xml.ws_2.1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.xml.rpc_1.2.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\monfox.dsnmp.agent_1.1.0.0_4-7-30.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\cryptoj.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.serp_1.14.4.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.beaninfo_2.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.descriptor_1.10.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.asm_1.1.0.0_3-2-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.asm.commons_1.1.0.0_3-2-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.asm.tree_1.1.0.0_3-2-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.repackaged.asm.util_1.1.0.0_3-2-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.jfr_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.core_2.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.logging_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.query_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.instrumentor_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.instrumentor.config_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.flightrecorder_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.notifications_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.diagnostics.snmp_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.i18n.generator_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.i18n.tools_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.management.jmx_1.4.2.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.mbean.maker_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.mbean.support_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.messaging.kernel_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.resourcepool_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.socket.api_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.wls_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.lifecycle_1.5.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.store_1.8.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.store.gxa_1.7.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.store.admintool_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.store.jdbc_1.3.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils.agent_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils.compiler_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.utils.expressions_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.timers_1.7.1.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.workmanager_1.11.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.jatmi_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security_1.0.0.0_6-2-0-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.auth_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.digest_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.identity_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.logger_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.psm_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.weblogic.security.ssl_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.nodemanager.plugin_1.3.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.core.nodemanager.process_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.jmspool_1.9.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.compat.wl.90_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.http.pubsub.mbean_1.7.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.redef_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.redefagent_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.redef.binding_1.6.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.toplink_1.1.0.0_11-1-1-6-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\org.eclipse.persistence_1.2.0.0_2-3.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\commonj.sdo_1.0.0.0_1-0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.core.coherence.descriptor_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.core.coherence.descriptor.binding_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.core.weblogic.msgcat_1.2.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\ws.api_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.core.eclipselink.integration_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.weblogic.sca.client_1.0.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.weblogic.rac.ucp_1.1.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\features\weblogic.server.modules_10.3.6.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\schema\weblogic-domain-binding.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\schema\weblogic-domain-binding-compatibility.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\schema\diagnostics-binding.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\schema\diagnostics-image-binding.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wlcipher.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\webservices.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\xmlx.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\ojdbc6.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\ons.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\ucp.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\aqapi.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\EccpressoAsn1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\EccpressoCore.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\EccpressoJcae.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\mysql-connector-java-commercial-5.1.17-bin.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wlsqlserver.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wldb2.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wlsybase.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wlinformix.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\fmwgenerictoken.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\wlw-langx.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\jcom.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-de.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-es.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-fr.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-it.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-ja.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-ko.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-pt_BR.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-zh_CN.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-zh_TW.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic-L10N.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\wlserver_10.3\server\lib\weblogic.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.osdt_11.1.1\osdt_xmlsec.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_jrf.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.odl_11.1.1\ojdl.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\loggers\ODL\1.0.0\lib\epml.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.dms_11.1.1\dms.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\ADM\11.1.2.0\lib\adm.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\ADM\11.1.2.0\lib\ap.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\ADM\11.1.2.0\lib\
copy F:\Oracle\Middleware\EPMSystem11R1\common\ADM\11.1.2.0\APS\11.1.2.0\admaps.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\ADM\11.1.2.0\ODBO\11.1.2.0\admodbo.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\essbase-studio-sdk\11.1.2.0\lib\cpld.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\EssbaseJavaAPI\11.1.2.0\lib\ess_es_server.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\EssbaseJavaAPI\11.1.2.0\lib\ess_japi.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.bea.core.apache.log4j_1.2.13.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.mail_1.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\ArtifactListing.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\LCMXMLBeans.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\registration_xmlBeans.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\sourceInfo.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\xbean.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\wsplugin.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\essbaseplugin.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\XML\AXIOM\1.2.6\axiom-api-1.2.10.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\XML\AXIOM\1.2.6\axiom-impl-1.2.10.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\lcm-clu.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\cssimportexport.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\backport-util-concurrent.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\broker-provider.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\json.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\jsr173_1.0_api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\resolver.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\xmlpublic.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\XmlSchema-1.3.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\opencsv-1.8.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\jdom.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\misc\11.1.2.0\servlet-api.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\bsf.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_misc.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\raframeworkrt\11.1.2.0\lib\eiengine.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\raframeworkrt\11.1.2.0\lib\foundation.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\raframeworkrt\11.1.2.0\lib\iona63.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\raframeworkrt\11.1.2.0\lib\comutil1_01.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\raframeworkrt\11.1.2.0\lib\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\quartz.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\castor-1.3.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\scheduler_ces.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\wf_eng_server.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\FCMProxy\11.1.2.0\LCMAMService-Client.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\SharedServices\11.1.2.0\lib\castor-1.3.1-core.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\javax.activation_1.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis-ant.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\saaj.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis-jaxrpc-1.2.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis2-adb-1.5.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis2-kernel-1.5.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis2-transport-local-1.5.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\axis2-transport-http-1.5.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\httpcore-4.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\Axis\1.6.2\lib\neethi-2.0.4.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\modules\com.oracle.ws.orawsdl_1.4.0.0.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_axis.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\utilities\LCM\11.1.2.0\lib\essbasestudioplugin.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_lcm.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\stellant\11.1.2.0\oracle-ridc-client-10g.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_stellant.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jsf_1.2.9\glassfish.jstl_1.2.0.1.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\oracle_common\modules\oracle.jmx_11.1.1\jmxspi.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_j2se.jar  z:\pablo\lib\EPM4\
copy F:\Oracle\Middleware\EPMSystem11R1\common\jlib\11.1.2.0\epm_thrift.jar  z:\pablo\lib\EPM4\
